version: '3.6'

services:
  # application & web server
  app:
    image: my/app:%COMMIT_HASH%
    deploy:
      %app_replicas: 1%
      restart_policy:
        max_attempts: 5
        delay: 5s
    volumes:
      - ./app:/data/app
    env_file: postgres/env
    entrypoint: sh entry.sh

  nginx:
    image: my/nginx:%COMMIT_HASH%
    deploy:
      replicas: 1
    ports:
      - 80:80
    volumes:
      - ./app:/data/app
      - ./nginx/logs:/var/log/nginx

  # database & caching
  postgres:
    image: postgres:10.3-alpine
    deploy:
      replicas: 1
    volumes:
      - ./postgres/storage:/var/lib/postgresql/data
    env_file: postgres/env

  memcached:
    image: memcached:1.5-alpine
    deploy:
      replicas: 1
    entrypoint:
      - memcached
      - -m 64
