version: '3.6'

services:
  # application & web server
  app:
    image: %REGISTRY_URL%/app:%COMMIT_HASH%
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        max_attempts: 5
        delay: 5s
    env_file: app/env
    volumes:
      - ./app:/data/app
    entrypoint: sh app.sh

  nginx:
    image: %REGISTRY_URL%/nginx:%COMMIT_HASH%
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 5
        delay: 5s
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./tls/nginx:/tls
      - ./app:/data/app
      - ./nginx/logs:/var/log/nginx
    entrypoint: sh nginx.sh

  # caching
  memcached:
    image: memcached:1.5-alpine
    deploy:
      replicas: 1
    entrypoint:
      - memcached
      - -m 64

networks:
  default:
    external:
      name: %APP_NAME%_network
